[package]

name = "substudy"
version = "0.4.2"
authors = ["Eric Kidd <git@randomhacks.net>"]
license = "CC0-1.0"

description = """Language-learning tools for working with parallel, bilingual
subtitles and media files."""

homepage = "http://www.randomhacks.net/substudy/"
documentation = "http://docs.rs/substudy"
repository = "https://github.com/emk/substudy"
readme = "README.md"
keywords = ["text"]

exclude = ["fixtures/empty.mp4"]

[dependencies]
cld2 = "1.0.1"
csv = "0.14.3"
docopt = "0.6.76"
encoding = "0.2.32"
env_logger = "0.3.2"
error-chain = "0.10"
handlebars = "0.11.3"
lazy_static = "0.1.15"
log = "0.3.3"
num = "0.1.28"
rustc-serialize = "0.3.16"
regex = "0.1.41"
uchardet = "2.0.0"

[dev-dependencies]
cli_test_dir = "0.1.2"
difference = "0.4.1"

[[bin]]
name = "substudy"
test = false
doc = false
